---
deployment:
      tasks:
        - export DEPLOYPATH=/home/wawanzon/public_html/ngeyogja
        - /bin/cp -R assets $DEPLOYPATH
        - /bin/cp -R css $DEPLOYPATH
        - /bin/cp -R img $DEPLOYPATH
        - /bin/cp -R js $DEPLOYPATH
        - /bin/cp index.html $DEPLOYPATH